### ISSUE TITLE
UMD bundle is published to npm

### ISSUE THREAD

**Issue by cristiano-belloni** [websdk/nap#25]
This, among the other things, breaks Webpack (`require` is overwritten).

I guess we shouldn't publish the UMD build at all, but just make available the CommonJS module in `src`, when publishing.

**Comment by mstade** [comment]
Wow, that was unexpected. I'll look into it, but my knee-jerk reaction given the description is that webpack is broken and no – we shouldn't expect consumers to have to deal with the source at all. That said, I don't actually _know_ so I'll have to investigate before truly taking a stand one way or the other. Thanks for reporting this buddy, and sorry for the inconvenience – I had no idea.

**Comment by cristiano-belloni** [comment]
Sorry, this is not the real issue. I'll open another.
